/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.entities.Train;
import org.example.entities.User;
import org.example.services.UserBookingService;
import org.example.util.UserServiceUtil;

import java.io.IOException;
import java.util.*;

public class App {

    public static void main(String[] args){
        System.out.println("Running Train Booking System");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try {
            //System.out.println("Running Train Booking System");
            userBookingService = new UserBookingService();
            //System.out.println("Running Train Booking System");
        }catch(IOException ex){
            System.out.println("something wrong");
            ex.printStackTrace();
            return;
        }
        Train trainSelectedForBooking = null;

        while(option != 7){
            System.out.println("choose the option:");
            System.out.println("1.sign up");
            System.out.println("2.login");
            System.out.println("3.Fetch Bookings");
            System.out.println("4.search trains");
            System.out.println("5.Book a seat");
            System.out.println("6.Cancel my bookings");
            System.out.println("7. exit the app");
            option = scanner.nextInt();
            //Train trainSelectedForBooking = new Train();
            switch(option){
                case 1:
                    System.out.println("Enter the username to signup");
                    String nameToSignUp = scanner.next();
                    System.out.println("Enter the password to signUp");
                    String passwordToSignUp = scanner.next();
                    User userToSignUp = new User(nameToSignUp,passwordToSignUp, UserServiceUtil.hashPassword(passwordToSignUp),new ArrayList<>(),UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter username");
                    String nameToLogin = scanner.next();
                    System.out.println("Enter password");
                    String passwordToLogin = scanner.next();

                    User userToLogin = new User(nameToLogin, passwordToLogin,
                            UserServiceUtil.hashPassword(passwordToLogin),
                            new ArrayList<>(), UUID.randomUUID().toString());

                    try {
                        UserBookingService temp = new UserBookingService(userToLogin);
                        if (temp.loginUser()) {
                            userBookingService = temp;
                            System.out.println("Login successful!");
                        } else {
                            System.out.println("Invalid username/password!");
                        }
                    } catch (IOException ex) {
                        System.out.println("Error reading user database.");
                        return;
                    }
                    break;


                case 3:
                    System.out.println("Fetching your bookings");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Type your source station");
                    String source = scanner.next();
                    System.out.println("Type your destination station");
                    String dest = scanner.next();

                    List<Train> trains = userBookingService.getTrains(source, dest);

                    if (trains.isEmpty()) {
                        System.out.println("No trains found!");
                        break;
                    }

                    int index = 1;
                    for (Train t : trains) {
                        System.out.println(index + ") Train ID : " + t.getTrainId());
                        t.getStationTimes().forEach((st, tm) -> {
                            System.out.println("   " + st + " -> " + tm);
                        });
                        index++;
                    }

                    System.out.println("Select a train by typing the number:");

                    int choice = scanner.nextInt();
                    if (choice < 1 || choice > trains.size()) {
                        System.out.println("Invalid choice");
                        break;
                    }

                    trainSelectedForBooking = trains.get(choice - 1);
                    System.out.println("Train selected: " + trainSelectedForBooking.getTrainId());
                    break;

                case 5:
                    if (trainSelectedForBooking == null) {
                        System.out.println("Please search and select a train first (Option 4)");
                        break;
                    }

                    System.out.println("Available seats (0 = Free, 1 = Booked)");
                    List<List<Integer>> seats = userBookingService.fetchSeats(trainSelectedForBooking);

                    for (List<Integer> rowList : seats) {
                        for (Integer val : rowList) {
                            System.out.print(val + " ");
                        }
                        System.out.println();
                    }

                    System.out.println("Enter row number:");
                    int row = scanner.nextInt();
                    System.out.println("Enter column number:");
                    int col = scanner.nextInt();

                    Boolean booked = userBookingService.bookTrainSeat(trainSelectedForBooking, row, col);

                    if (booked) {
                        System.out.println("Seat booked successfully!");
                    } else {
                        System.out.println("Seat cannot be booked.");
                    }

                    break;

                case 6:
                    System.out.println("Enter ticket ID to cancel:");
                    String ticketIdToCancel = scanner.next();

                    Boolean cancelled = userBookingService.cancelBooking(ticketIdToCancel);

                    if (cancelled) {
                        System.out.println("Your ticket has been cancelled.");
                    } else {
                        System.out.println("No such ticket found!");
                    }

                    break;

                default:
                    break;
            }
        }
    }
}